{% set name = "CutLang" %}
{% set version = '2.15.1' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

build:
  number: 0
  skip: True  # [win]

requirements:
  host:
    - root ==6.30.02
    - onnxruntime-cpp
    - jupyterlab >=4,<5
    - metakernel >=0.30,<1
    - flex >=2.6
    - bison >=3.8
    - make
    - wget
  run:
    - root ==6.30.02
    - onnxruntime-cpp
    - jupyterlab >=4,<5
    - metakernel >=0.30,<1
    - wget

about:
  home: 'https://github.com/unelg/CutLang'
  license: LGPL-2.1-only
  #license_file: LICENSE
  summary: |
    A Particle Physics Analysis Description Language and Runtime Interpreter
  description: |
    A Particle Physics Analysis Description Language and Runtime Interpreter

extra:
  recipe-maintainers:
    - unelg
    - ahmetcansansar
