#!/bin/bash

set -e

notebook_env=$CONDA_DIR/envs/notebook
CUTLANG_PATH=$notebook_env/bin/cutlang

touch $CUTLANG_PATH/mybinder_true

jupyterConfigDir=$(jupyter --config-dir)

mkdir -p $jupyterConfigDir

cp ~/binder/jupyter_notebook_config.py $jupyterConfigDir/jupyter_notebook_config.py