#!/bin/bash

export notebook_env=$CONDA_DIR/envs/notebook
export CUTLANG_PATH=$notebook_env/bin/cutlang
export PATH=$CUTLANG_PATH/runs:$PATH
export CUTLANG_JUPYTER_DATA_DIR=$(jupyter --data-dir)

mkdir -p $CUTLANG_JUPYTER_DATA_DIR/kernels/cutlang

cp $CUTLANG_PATH/kernel/kernel.json $CUTLANG_JUPYTER_DATA_DIR/kernels/cutlang/kernel.json

cp $CUTLANG_PATH/kernel/magics/cutlangmagic.py $notebook_env/lib/JupyROOT/kernel/magics/cutlangmagic.py 2>>/dev/null
cp $CUTLANG_PATH/kernel/magics/cutlangmagic.py $notebook_env/lib/python3.9/site-packages/JupyROOT/kernel/magics/cutlangmagic.py 2>>/dev/null
cp $CUTLANG_PATH/kernel/magics/cutlangmagic.py $notebook_env/lib/python3.8/site-packages/JupyROOT/kernel/magics/cutlangmagic.py 2>>/dev/null
cp $CUTLANG_PATH/kernel/magics/cutlangmagic.py $notebook_env/lib/python3.7/site-packages/JupyROOT/kernel/magics/cutlangmagic.py 2>>/dev/null

cp $CUTLANG_PATH/kernel/magics/shellmagic.py $notebook_env/lib/JupyROOT/kernel/magics/shellmagic.py 2>>/dev/null
cp $CUTLANG_PATH/kernel/magics/shellmagic.py $notebook_env/lib/python3.9/site-packages/JupyROOT/kernel/magics/shellmagic.py 2>>/dev/null
cp $CUTLANG_PATH/kernel/magics/shellmagic.py $notebook_env/lib/python3.8/site-packages/JupyROOT/kernel/magics/shellmagic.py 2>>/dev/null
cp $CUTLANG_PATH/kernel/magics/shellmagic.py $notebook_env/lib/python3.7/site-packages/JupyROOT/kernel/magics/shellmagic.py 2>>/dev/null

cp $CUTLANG_PATH/kernel/cutlangmagic.py $notebook_env/lib/JupyROOT/magics/cutlangmagic.py 2>>/dev/null
cp $CUTLANG_PATH/kernel/cutlangmagic.py $notebook_env/lib/python3.9/site-packages/JupyROOT/magics/cutlangmagic.py 2>>/dev/null
cp $CUTLANG_PATH/kernel/cutlangmagic.py $notebook_env/lib/python3.8/site-packages/JupyROOT/magics/cutlangmagic.py 2>>/dev/null
cp $CUTLANG_PATH/kernel/cutlangmagic.py $notebook_env/lib/python3.7/site-packages/JupyROOT/magics/cutlangmagic.py 2>>/dev/null

cp $CUTLANG_PATH/kernel/shellmagic.py $notebook_env/lib/JupyROOT/magics/shellmagic.py 2>>/dev/null
cp $CUTLANG_PATH/kernel/shellmagic.py $notebook_env/lib/python3.9/site-packages/JupyROOT/magics/shellmagic.py 2>>/dev/null
cp $CUTLANG_PATH/kernel/shellmagic.py $notebook_env/lib/python3.8/site-packages/JupyROOT/magics/shellmagic.py 2>>/dev/null
cp $CUTLANG_PATH/kernel/shellmagic.py $notebook_env/lib/python3.7/site-packages/JupyROOT/magics/shellmagic.py 2>>/dev/null