name: Update conda package macos

on:
  push:
    branches:
      - 'master'
      - 'package_test'

jobs:
  build-conda-macos:
    
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '24'

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.11"
    - name: Update meta
      id: update_meta
      working-directory: ./scripts/conda
      shell: bash -l {0}
      run: |
        brew install gsed

        export version_cutlang=`cat ../../VERSION`
        echo "VERSION_CUTLANG=$version_cutlang" >> "$GITHUB_OUTPUT"

        echo "::group::VERSION"
        echo "Inside group $version_cutlang"
        echo "::endgroup::"
        
        gsed -i "/version = /c{% set version = '$version_cutlang' %}" meta.yaml
        gsed -i "/cout << \"CLA v/c cout << \"CLA v$version_cutlang\\\t\";" ../../CLA/CLA.Q
        gsed -i "/\"display_name\": \"ROOT C++ with CutLang/c    \"display_name\": \"ROOT C++ with CutLang v$version_cutlang\"," ../../scripts/jupyter/kernel/cutlangkernel.json
        meta=`cat ../../scripts/conda/meta.yaml`
        echo "::group::META"
        echo "Inside group $meta"
        echo "::endgroup::"
        
        export check_version_cutlang=$(conda search -c ${{secrets.PACKAGE_USERNAME}} -f cutlang 2>/dev/null | grep "$version_cutlang" || true)
        echo "CHECK_VERSION_CUTLANG=$check_version_cutlang" >> "$GITHUB_OUTPUT"
        
        # export unelgRepo=$(git remote get-url origin 2>/dev/null | grep -e 'unelg' || true)
        # echo "UNELG_REPO=$unelgRepo" >> "$GITHUB_OUTPUT"

    - name: chmod
      working-directory: .github/workflows
      run: |
        ls -la
        chmod +x update_conda_package_macos.sh
        chmod +x update_conda_package_macos_mail_success.js
        chmod +x update_conda_package_macos_mail_error.js

    - name: Build and upload conda macos
      if: ${{ !steps.update_meta.outputs.CHECK_VERSION_CUTLANG }}
      working-directory: ./.github/workflows
      shell: bash -l {0}
      run: |
        conda info
        conda install -y anaconda-client conda-build
        ./update_conda_package_macos.sh
      env:
        SUBDIR: "scripts/conda"
        ANACONDA_TOKEN: "${{ secrets.ANACONDA_TOKEN }}"
        PACKAGE_USERNAME: "${{ secrets.PACKAGE_USERNAME }}"

    #- name: SMTP
    #  if: ${{ !steps.update_meta.outputs.CHECK_VERSION_CUTLANG }}
    #  uses: peter-evans/sendgrid-action@v1
    #  env:
    #    SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
    #    SCRIPT_FILEPATH: ./.github/workflows/update_conda_package_macos_mail_success.js     
